---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install basic packages
      apt:
        name:
          - htop
          - vim
          - curl
        state: present

- hosts: webservers
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

- hosts: dbservers
  become: yes
  tasks:
    - name: Install MySQL
      apt:
        name: 
          - mysql-server
          - python3-pymysql
        state: present